name: Daily Commit

on:
  schedule:
    - cron: "0 13 * * *"

  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "bozzettomirko88@gmail.com"
          git config --local user.name "Mirko Bozzetto"

      - name: Update counter
        run: |
          if [ -f counter.txt ]; then
            COUNTER=$(cat counter.txt)
          else
            COUNTER=0
          fi
          COUNTER=$((COUNTER + 1))
          echo $COUNTER > counter.txt
          echo "Counter updated to: $COUNTER"

      - name: Generate commit message
        id: commit_msg
        run: |
          MESSAGES=(
            "Update daily progress"
            "Increment counter"
            "Daily update"
            "Update metrics"
            "Progress update"
            "Update tracker"
            "Daily commit"
            "Update statistics"
            "Routine update"
            "Update count"
          )
          RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
          MESSAGE="${MESSAGES[$RANDOM_INDEX]}"
          DATE=$(date +"%Y-%m-%d")
          FINAL_MESSAGE="$MESSAGE - $DATE"
          echo "message=$FINAL_MESSAGE" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |
          git add counter.txt
          git commit -m "${{ steps.commit_msg.outputs.message }}" || echo "No changes to commit"
          git push || echo "Nothing to push"
